### ISSUE TITLE
Is it possible to get the network transaction and address hash for crypto deposits?

### ISSUE THREAD

**Issue by npomfret** [AndrewRademacher/coinbase-exchange#8]

**Comment by ericpashman** [comment]
Coinbase has two sets of APIs, one for interacting with ordinary Coinbase accounts and another, entirely separate set, for interacting with trading accounts on the Coinbase Pro exchange (fka GDAX). (Actually, there's a third set now as well, for advanced trading functionality for institutional investors via Coinbase Prime.) This library implements only the trading APIs for Coinbase Pro.

You can get what you want by interacting with the API for ordinary accounts: the documentation is [here](https://developers.coinbase.com/api/v2). As far as I'm aware there isn't a Haskell library that implements it, but the docs list official and unofficial libraries for other languages.
